### ISSUE TITLE
"latest" tag?

### ISSUE THREAD

**Issue by barbequesauce** [jchonig/docker-mmonit#15]
Pulling for the first time and I was surprised that there was no `latest` tag on dockerhub. can this be implemented?

**Comment by stanthewizzard** [comment]
same issue

Error response from daemon: manifest for jchonig/mmonit:latest not found: manifest unknown: manifest unknown

**Comment by jchonig** [comment]
Sorry, I did not see this issue, I'll have to figure out why I am not getting notifications.

I do that explicitly for two reasons.

1. I haven't figured out how to automatically process tags (so when I push VERSION=4.2.1) to git it automatically builds 4.2.1 and latest
2. M/Monit upgrades sometimes go wrong, so I think they should be manually initiated.
