### ISSUE TITLE
Alerts hostname?

### ISSUE THREAD

**Issue by barbequesauce** [jchonig/docker-mmonit#16]
Hi - where can I set the hostname used in alerts?
<img width="1062" alt="Screenshot 2024-01-05 at 11 16 48 AM" src="https://github.com/jchonig/docker-mmonit/assets/25070944/f651e872-d6f1-4b24-b02d-a1334a67113b">

**Comment by jchonig** [comment]
This is not the place for M/Monit questions, only for issues directly related to the container.
