### ISSUE TITLE
Mmonit 4.2.0 very slow in use ....

### ISSUE THREAD

**Issue by roe1974** [jchonig/docker-mmonit#19]
As described above, I have updated on the Synology from 4.0.2 to 4.2.0. The container starts after a long "PRAGMA check" ... but the whole system responds very slow !! ... it takes minutes to load the different pages :-(

**Comment by jchonig** [comment]
This is not the place to report issues with M/Monit, only the container.

I also saw 4.2.0 being very slow and moved back to 4.0.2.
