### ISSUE TITLE
Mmonit 4.2.2 resolves performance issues

### ISSUE THREAD

**Issue by roe1974** [jchonig/docker-mmonit#20]
Please upgrade the docker container to 4.2.2.
Changes:
 
- we significantly improved the speed of statistics aggregation (the slower aggregation speed was the main performance difference between 4.0.2 and 4.1.0-4.2.0)
 
- we have increased the aggregation granularity and reduced the number of default datapoints in the analytics report from ~60 to ~30 for default timeframes, to reduce the data volume and load time  when large number of statistics is to be displayed (e.g. the 'all hosts' selection). The higher precision can be displayed via a selection in the chart.

thx a lot !!
br, Richard

**Comment by sseide** [comment]
do you mean 4.2.1? 4.2.2 is not release by now it seems:

https://mmonit.com/wiki/MMonit/Releases

Or is there an additional release coming these days?

**Comment by roe1974** [comment]
I got this link from mmonit support:

https://mmonit.com/tmp/mmonit-4.2.2-linux-x64.tar.gz

so i think 4.2.2 is coming soon
br richard

**Comment by sseide** [comment]
ok, thanks - but i think 4.2.1 docker image should be created non the less (if the new version has some other issues).

@jchonig can you please create a 4.2.1 docker image release? Thanks a lot.

**Comment by jchonig** [comment]
I have merged your PR (thanks) and am also building 4.2.2.

**Comment by jchonig** [comment]
I am unable to build 4.2.2 without changes to the container that I do not have time for at the moment.  Maybe later this weekend.

**Comment by jchonig** [comment]
Reopening

**Comment by sseide** [comment]
As v4.2.1 is available as docker image now (thanks!) and its release notes also mention some performance improvements, it is probably fine to wait until 4.2.2 is officially released. And than everything should work as before without changes needed...

**Comment by jchonig** [comment]
M/Monit 4.2.2 was released today and I built the 4.2.2 tag.

The upgrade took quite a long time, but it is up and running for me.

**Comment by roe1974** [comment]
Waiting here for about 45min an Mmonit is not starting ... the logs are full with:

2024-05-09 06:42:09,stdout,AssertException: Unsupported database schema version: 22 -- please run database upgrade script(s) to update M/Monit to version 4.2.2 (database schema version 23)

2024-05-09 06:42:09,stdout,Starting mmonit 4.2.2

2024-05-09 06:42:08,stdout,AssertException: Unsupported database schema version: 22 -- please run database upgrade script(s) to update M/Monit to version 4.2.2 (database schema version 23)

2024-05-09 06:42:07,stdout,Starting mmonit 4.2.2

2024-05-09 06:42:06,stdout,AssertException: Unsupported database schema version: 22 -- please run database upgrade script(s) to update M/Monit to version 4.2.2 (database schema version 23)

2024-05-09 06:42:06,stdout,Starting mmonit 4.2.2

2024-05-09 06:42:05,stdout,AssertException: Unsupported database schema version: 22 -- please run database upgrade script(s) to update M/Monit to version 4.2.2 (database schema version 23)

2024-05-09 06:42:05,stdout,Starting mmonit 4.2.2

2024-05-09 06:42:05,stdout,AssertException: Unsupported database schema version: 22 -- please run database upgrade script(s) to update M/Monit to version 4.2.2 (database schema version 23)

2024-05-09 06:42:04,stdout,Starting mmonit 4.2.2

2024-05-09 06:42:03,stdout,AssertException: Unsupported database schema version: 22 -- please run database upgrade script(s) to update M/Monit to version 4.2.2 (database schema version 23)

**Comment by sseide** [comment]
Please check the logs before this first AssertException to find the real error causing it.
I had big trouble updating to 4.2.0 because some table definitions changed and newly introduced foreign references could not be created due to now "invalid" data already existing inside my database.

I had to start the new container as interaktive session and run the upgrade script manually to see the real errors and fix it directly within the database and run script again until everything updated fine.

Am 9. Mai 2024 06:56:36 UTC schrieb Richard ***@***.***>:

**Comment by jchonig** [comment]
Did you interrupt the first start because it was taking too long?  My first start probably took an hour (I didn't time it) with lots of:

```
mmonit_mmonit  | Upgrading M/Monit from /config/mmonit-4.2.1-alpine to /config/mmonit-4.2.2 ...
mmonit_mmonit  |
mmonit_mmonit  | ***WARNING*** please wait and DO NOT INTERRUPT the process (the upgrade can take some time if your database is large)
mmonit_mmonit  |
mmonit_mmonit  | Reading license in '/config/mmonit-4.2.1-alpine/conf/server.xml'
mmonit_mmonit  | Starting Reactor using epoll (max concurrent connections = 4096)
mmonit_mmonit  | Copying database file from /config/mmonit-4.2.1-alpine/db/mmonit.db to /config/mmonit-4.2.2/db/ ... Reactor stopped
mmonit_mmonit  | Connecting to sqlite:///config/mmonit-4.2.2/db/mmonit.db?synchronous=full&
mmonit_mmonit  | Upgrading schema version 22 to 23
mmonit_mmonit  | 	Add analytics table with 2m precision
mmonit_mmonit  | CREATE TABLE statistics_aggregate_2m (
mmonit_mmonit  |   statisticsid INTEGER,
mmonit_mmonit  |   collectedsec INTEGER NOT NULL,
mmonit_mmonit  |   value_avg REAL,
mmonit_mmonit  |   count INTEGER,
mmonit_mmonit  |   CONSTRAINT statistics_aggregate_2m_statisticsid_fk FOREIGN KEY(statisticsid) REFERENCES statistics(id) ON DELETE CASCADE
mmonit_mmonit  | );
mmonit_mmonit  |
```

I can probably figure out some way to see if the first start was interrupted and cause the upgrade to be re-run on the next start.

**Comment by roe1974** [comment]
for me the solution was 4.0.2 -> 4.2.1 -> 4.2.2 ... that worked for me :-)
br, Richard
