### ISSUE TITLE
Version 4.3.0

### ISSUE THREAD

**Issue by roe1974** [jchonig/docker-mmonit#29]
Hey @jchonig :-)
Please push Version 4.3.0 to Docker Hub, thx !
br, Richard ;-)

PS: what is backup-4.3.0 Version ?

**Comment by jchonig** [comment]
I was waiting for M/Monit support to fix an upgrade bug with 4.3.0, it appears to work now.

the -backup version has code to automatically backup the databases periodically.  I also added code to do a full backup before upgrading and if the upgrade fails to restore from the backup.
