### ISSUE TITLE
4.3.1 not starting ?!?

### ISSUE THREAD

**Issue by roe1974** [jchonig/docker-mmonit#30]
i just migrated from 4.3.0 to 4.3.1 ... log looks OK but ends with:
"Starting mmonit 4.3.1"
... thats it ...
website not reachable ... missing "mmonit 4.3.1 started"
Anyone else this problem ?
br, RIchard

**Comment by jchonig** [comment]
It is running fine here.  Although I am on the backups-4.3.1 branch, that only has additions.

Anything in the mmonit log files?

**Comment by roe1974** [comment]
Everything OK here in the meantime :-)
it took almost 10min from ‘starting’ to ‘started’ ... maybe I should migrate slowly to SSD ;-)
