### ISSUE TITLE
4.3.2 not starting ... unsupported database shema

### ISSUE THREAD

**Issue by roe1974** [jchonig/docker-mmonit#31]
The new Version 4.3.2 is not starting .... an error comes:
AssertException: Unsupported database schema version: 24
How the schema update can be done ?
br, Richard
<img width="944" alt="Bildschirmfoto 2024-11-06 um 08 39 45" src="https://github.com/user-attachments/assets/79af023b-5e42-4451-b074-45d0722703a7">

**Comment by jchonig** [comment]
Do you have a full log of that run?

**Comment by roe1974** [comment]
Strange ... The second time it worked ... the log now also says that he did the schema upgrade to 25 ... strange :-P
Sorry for the misreport ;-)

**Comment by jchonig** [comment]
I don't believe in glitches.  So the next time it happens, please provide a
full log.

Thanks

Jeff

-- 
Jeffrey C. Honig ***@***.***>
http://jch.honig.net
PGP ID: A96C148E8B0E5F741A90ED04BBE5FFC5E52718CE
<https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa96c148e8b0e5f741a90ed04bbe5ffc5e52718ce>
Keybase: jchonig <https://keybase.io/jchonig>
Secure E-mail <https://protonmail.com>: ***@***.***

**Comment by roe1974** [comment]
👍
